<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\BonusType;
use App\Models\Relic;
use App\Models\Tier;
use Illuminate\Database\Seeder;

class RelicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $relics = [
            [
                'name'             => 'No Spoon',
                'tier'             => 'Rare',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Matrix event',
            ],
            [
                'name'             => 'Copper Badge',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 3,
                'unlock_condition' => 'Finish P4 in Copper',
            ],
            [
                'name'             => 'Silver Badge',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => 'Finish P4 in Silver',
            ],
            [
                'name'             => 'T:I Flux',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Beat w4500 in T1',
            ],
            [
                'name'             => 'T:II Lumin',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 1.5,
                'unlock_condition' => 'Beat w4500 in T2',
            ],
            [
                'name'             => 'T:III Pulse',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Beat w4500 in T3',
            ],
            [
                'name'             => 'T:IV Harmonic',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Beat w4500 in T4',
            ],
            [
                'name'             => 'T:V Ether',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Beat w4500 in T5',
            ],
            [
                'name'             => '1st Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Play for 1 year',
            ],
            [
                'name'             => '2nd Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Play for 2 year',
            ],
            [
                'name'             => '3rd Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Play for 3 year',
            ],
            [
                'name'             => '4th Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Play for 4 year',
            ],
            [
                'name'             => '5th Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Play for 5 year',
            ],
            [
                'name'             => '6th Tower Birthday',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Play for 6 year',
            ],
            [
                'name'             => 'Dreamcatcher',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Howling Wolf event',
            ],
            [
                'name'             => 'Bacteriophage',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Viral Outbreak event',
            ],
            [
                'name'             => 'Ionized Plasma',
                'tier'             => 'Rare',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Plasma Returns event',
            ],
            [
                'name'             => 'Ancient Tome',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 1.5,
                'unlock_condition' => 'Earn 350 medals Sands of Time event',
            ],
            [
                'name'             => 'Tower Latte',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Autumn event',
            ],
            [
                'name'             => 'Spooky Bat',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Halloween event',
            ],
            [
                'name'             => 'Cherry',
                'tier'             => 'Rare',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Cherry Blossom event',
            ],
            [
                'name'             => 'Holy Joystick',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Retro Arcade event',
            ],
            [
                'name'             => 'Honey Drop',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Honey event',
            ],
            [
                'name'             => 'Firework',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals New Year event',
            ],
            [
                'name'             => 'Aurora Vortex',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Aurora event',
            ],
            [
                'name'             => 'Dark Sight',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Dark Strands event',
            ],
            [
                'name'             => 'Palm Tree',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Retrowave event',
            ],
            [
                'name'             => 'Submarine',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Deep Blue Sea event',
            ],
            [
                'name'             => 'Alien Head',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Aliens event',
            ],
            [
                'name'             => 'Warp Gate',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Faster Than Light event',
            ],
            [
                'name'             => 'Barnacle',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Ocean Night event',
            ],
            [
                'name'             => 'Pizza',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Invaders event',
            ],
            [
                'name'             => 'Refraction Array',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Prismatic Lines event',
            ],
            [
                'name'             => 'Hook',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Sunset Fishing event',
            ],
            [
                'name'             => 'Cobweb',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Cobweb event',
            ],
            [
                'name'             => 'Gale Winds',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Eye of the Storm event',
            ],
            [
                'name'             => 'Clip Ons',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Into the Matrix event',
            ],
            [
                'name'             => 'Rain Jacket',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Storm event',
            ],
            [
                'name'             => 'Rabies',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Viral Outbreak (II) event',
            ],
            [
                'name'             => 'Comet',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Interstellar event',
            ],
            [
                'name'             => 'Remote Control',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Tower\'s Channel event',
            ],
            [
                'name'             => 'Anubis',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Sands of (II) Time event',
            ],
            [
                'name'             => 'Lava Flow',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Volcano Event',
            ],
            [
                'name'             => 'Abduction Room',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Abduction Event',
            ],
            [
                'name'             => 'Acorn',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Autumn event',
            ],
            [
                'name'             => 'Cauldron',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Halloween (II) event',
            ],
            [
                'name'             => 'Icicle',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Snowstorm Event',
            ],
            [
                'name'             => 'Koi Fish',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Cherry Blossom (II) event',
            ],
            [
                'name'             => 'Tea Ceremony',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => '200 medals Purchase Cherry Blossom (II) event',
            ],
            [
                'name'             => 'Lunar Cat Paw',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Chance',
                'value'            => 1,
                'unlock_condition' => 'Earn 350 medals Meowy Night event',
            ],
            [
                'name'             => 'Confetti Ball',
                'tier'             => 'Rare',
                'bonus_type'       => 'Free Attack Upgrade',
                'value'            => 1,
                'unlock_condition' => 'Earn 350 medals New Year (II) event',
            ],
            [
                'name'             => 'Summit Starlight',
                'tier'             => 'Rare',
                'bonus_type'       => 'Lab Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Howling Wolf (II) event',
            ],
            [
                'name'             => 'Falling Apple',
                'tier'             => 'Rare',
                'bonus_type'       => 'Free Defense Upgrade',
                'value'            => 1,
                'unlock_condition' => 'Earn 350 medals Gravity event',
            ],
            [
                'name'             => 'Power Glove',
                'tier'             => 'Rare',
                'bonus_type'       => 'Damage',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Retro Arcade (II) event',
            ],
            [
                'name'             => 'Coral Crown',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health Regen',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Deep Blue Sea (II) event',
            ],
            [
                'name'             => 'Temporal Rift',
                'tier'             => 'Rare',
                'bonus_type'       => 'Cash',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals What Time Is It? event',
            ],
            [
                'name'             => 'Hourglass',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Premium 550 medals What Time Is It? event',
            ],
            [
                'name'             => 'Throne',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health',
                'value'            => 2,
                'unlock_condition' => 'Earn 75 guild tokens Guild Season 1',
            ],
            [
                'name'             => 'Haunted Mirror',
                'tier'             => 'Rare',
                'bonus_type'       => 'Wall Rebuild',
                'value'            => 2.00,
                'unlock_condition' => 'Earn 350 medals Dark Strands (II) event',
            ],
            [
                'name'             => 'Whispering Web',
                'tier'             => 'Rare',
                'bonus_type'       => 'Free Defense Upgrade',
                'value'            => 1,
                'unlock_condition' => 'Premium 550 medals Dark Strands (II) event',
            ],
            [
                'name'             => 'Pulsar Core',
                'tier'             => 'Rare',
                'bonus_type'       => 'Recovery Amount',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Faster Than Light (II) event',
            ],
            [
                'name'             => 'Quantum Drive',
                'tier'             => 'Rare',
                'bonus_type'       => 'Bot Range',
                'value'            => 1.00,
                'unlock_condition' => 'Premium 550 medals Faster Than Light (II) event',
            ],
            [
                'name'             => 'Bloom Burst',
                'tier'             => 'Rare',
                'bonus_type'       => 'Cash',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Easter event',
            ],
            [
                'name'             => 'Mystic Hair',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Premium 550 medals Easter event',
            ],
            [
                'name'             => 'Fancy Wires',
                'tier'             => 'Rare',
                'bonus_type'       => 'Health Regen',
                'value'            => 2,
                'unlock_condition' => 'Spend 75 guild tokens Guild Season 2',
            ],
            [
                'name'             => 'Infinite Ruler',
                'tier'             => 'Rare',
                'bonus_type'       => 'Free Utility Upgrade',
                'value'            => 1,
                'unlock_condition' => 'Earn 350 medals Pi event',
            ],
            [
                'name'             => 'Pi Seal',
                'tier'             => 'Rare',
                'bonus_type'       => 'Coins',
                'value'            => 2,
                'unlock_condition' => 'Premium 550 medals Pi event',
            ],
            [
                'name'             => 'UFO Beam',
                'tier'             => 'Rare',
                'bonus_type'       => 'Knockback Force',
                'value'            => 2,
                'unlock_condition' => 'Earn 350 medals Invaders event',
            ],
            [
                'name'             => 'Abduction Signal',
                'tier'             => 'Rare',
                'bonus_type'       => 'Crit Factor',
                'value'            => 2,
                'unlock_condition' => 'Premium 550 medals Invaders event',
            ],
            [
                'name'             => 'Red Pill',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Matrix event',
            ],
            [
                'name'             => 'Gold Badge',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Finish P4 in Gold',
            ],
            [
                'name'             => 'Platinum Badge',
                'tier'             => 'Epic',
                'bonus_type'       => 'Lab Speed',
                'value'            => 4,
                'unlock_condition' => 'Finish P4 in Platinum',
            ],
            [
                'name'             => 'T: VI Nova',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Beat w4500 in T6',
            ],
            [
                'name'             => 'T: VII Aether',
                'tier'             => 'Epic',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => 'Beat w4500 in T7',
            ],
            [
                'name'             => 'T: VIII Graviton',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 5,
                'unlock_condition' => 'Beat w4500 in T8',
            ],
            [
                'name'             => 'T: IX Fusion',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Beat w4500 in T9',
            ],
            [
                'name'             => 'T: X Plasma',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 5,
                'unlock_condition' => 'Beat w4500 in T10',
            ],
            [
                'name'             => 'Spirit Wolf',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Howling Wolf event',
            ],
            [
                'name'             => 'Neuron',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Viral Outbreak event',
            ],
            [
                'name'             => 'Plasma Arc',
                'tier'             => 'Epic',
                'bonus_type'       => 'Lab Speed',
                'value'            => 4,
                'unlock_condition' => 'Earn 700 medals Plasma Returns event',
            ],
            [
                'name'             => 'Space Sundial',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Sands of Time event',
            ],
            [
                'name'             => 'Pumpkin',
                'tier'             => 'Epic',
                'bonus_type'       => 'Lab Speed',
                'value'            => 4,
                'unlock_condition' => 'Earn 700 medals Autumn event',
            ],
            [
                'name'             => 'Man Skull',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Halloween event',
            ],
            [
                'name'             => 'Sakura Lantern',
                'tier'             => 'Epic',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Cherry Blossom event',
            ],
            [
                'name'             => 'Controller',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Retro Arcade event',
            ],
            [
                'name'             => 'Stinger',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Honey event',
            ],
            [
                'name'             => 'Cheers',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals New Year event',
            ],
            [
                'name'             => 'Contained Ions',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Aurora event',
            ],
            [
                'name'             => 'Creepy Smile',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Dark Strands event',
            ],
            [
                'name'             => 'Pixel Cube Heart',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Retrowave event',
            ],
            [
                'name'             => 'The Kraken',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Deep Blue Sea event',
            ],
            [
                'name'             => 'Alien Warp Drive',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Aliens event',
            ],
            [
                'name'             => 'Star Ship',
                'tier'             => 'Epic',
                'bonus_type'       => 'Lab Speed',
                'value'            => 4,
                'unlock_condition' => 'Earn 700 medals Faster Than Light event',
            ],
            [
                'name'             => 'Wave',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Ocean Night event',
            ],
            [
                'name'             => 'Illuminati',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Invaders event',
            ],
            [
                'name'             => 'Prismatic Shard',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Prismatic Lines event',
            ],
            [
                'name'             => 'Fish',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Sunset Fishing event',
            ],
            [
                'name'             => 'The Fly',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Cobweb event',
            ],
            [
                'name'             => 'Flying House',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Eye of the Storm event',
            ],
            [
                'name'             => 'Code Stream',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Into the Matrix event',
            ],
            [
                'name'             => 'Cloud Lightning',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Storm event',
            ],
            [
                'name'             => 'Ebola',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Viral Outbreak (II) event',
            ],
            [
                'name'             => 'Planetary Rings',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Interstellar event',
            ],
            [
                'name'             => 'Cathode Ray Tube',
                'tier'             => 'Epic',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Tower\'s Channel event',
            ],
            [
                'name'             => 'Sphinx',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Sands of Time (II) event',
            ],
            [
                'name'             => 'Ash Cloud',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Volcano Event',
            ],
            [
                'name'             => 'Crop Circle',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Abduction Event',
            ],
            [
                'name'             => 'Scarf',
                'tier'             => 'Epic',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Autumn event',
            ],
            [
                'name'             => 'Witch Hat',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Halloween event',
            ],
            [
                'name'             => 'Sleigh Bell',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Snowstorm event',
            ],
            [
                'name'             => 'Bonsai Tree',
                'tier'             => 'Epic',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Cherry Blossom (II) event',
            ],
            [
                'name'             => 'Kimono',
                'tier'             => 'Epic',
                'bonus_type'       => 'Coins',
                'value'            => 5,
                'unlock_condition' => '500 medals Purchase Cherry Blossom (II) event',
            ],
            [
                'name'             => 'Pet Cat',
                'tier'             => 'Epic',
                'bonus_type'       => 'Attack Speed',
                'value'            => 2,
                'unlock_condition' => 'Earn 700 medals Meowy Night event',
            ],
            [
                'name'             => 'Party Mask',
                'tier'             => 'Epic',
                'bonus_type'       => 'Ultimate Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals New Year (II) event',
            ],
            [
                'name'             => 'Mountain Goat',
                'tier'             => 'Epic',
                'bonus_type'       => 'Health',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Howling Wolf (II) event',
            ],
            [
                'name'             => '3 Body Solution',
                'tier'             => 'Epic',
                'bonus_type'       => 'Super Critical Chance',
                'value'            => 2,
                'unlock_condition' => 'Earn 700 medals Gravity event',
            ],
            [
                'name'             => 'Arcade Token',
                'tier'             => 'Epic',
                'bonus_type'       => 'Bot Range',
                'value'            => 2.00,
                'unlock_condition' => 'Earn 700 medals Retro Arcade (II) event',
            ],
            [
                'name'             => 'Angler Fish',
                'tier'             => 'Epic',
                'bonus_type'       => 'Thorns',
                'value'            => 2,
                'unlock_condition' => 'Earn 700 medals Deep Blue Sea (II) event',
            ],
            [
                'name'             => 'Crown',
                'tier'             => 'Epic',
                'bonus_type'       => 'Crit Factor',
                'value'            => 5,
                'unlock_condition' => 'Spend 150 Tokens in Guild Season 1',
            ],
            [
                'name'             => 'Dream Clock',
                'tier'             => 'Epic',
                'bonus_type'       => 'Orb Speed',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals What Time Is It? event',
            ],
            [
                'name'             => 'Time Compass',
                'tier'             => 'Epic',
                'bonus_type'       => 'Attack Speed',
                'value'            => 2,
                'unlock_condition' => 'Premium 1100 medals What Time Is It? event',
            ],
            [
                'name'             => 'Shadow Puppet',
                'tier'             => 'Epic',
                'bonus_type'       => 'Super Critical Mult',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Dark Strands (II) event',
            ],
            [
                'name'             => 'Cursed Candle',
                'tier'             => 'Epic',
                'bonus_type'       => 'Super Critical Chance',
                'value'            => 2,
                'unlock_condition' => 'Premium 1100 medals Dark Strands (II) event',
            ],
            [
                'name'             => 'Light Speedometer',
                'tier'             => 'Epic',
                'bonus_type'       => 'Enemy Attack Level Skip',
                'value'            => 2,
                'unlock_condition' => 'Earn 700 medals  Faster Than Light (II) event',
            ],
            [
                'name'             => 'Photon Blade',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Premium 1100 medals Faster Than Light (II)  event',
            ],
            [
                'name'             => 'Candy Core',
                'tier'             => 'Epic',
                'bonus_type'       => 'Damage',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Easter event',
            ],
            [
                'name'             => 'Magic Egg',
                'tier'             => 'Epic',
                'bonus_type'       => 'Free Attack Upgrade',
                'value'            => 2,
                'unlock_condition' => 'Premium 1100 medals Easter event',
            ],
            [
                'name'             => 'Mech Head',
                'tier'             => 'Epic',
                'bonus_type'       => 'Bot Range',
                'value'            => 2.00,
                'unlock_condition' => 'Spend 150 Tokens in Guild Season 2',
            ],
            [
                'name'             => 'Do While True',
                'tier'             => 'Epic',
                'bonus_type'       => 'Orb Speed',
                'value'            => 5,
                'unlock_condition' => 'Earn 700 medals Pi event',
            ],
            [
                'name'             => 'Psychohistorian Brain',
                'tier'             => 'Epic',
                'bonus_type'       => 'Super Critical Chance',
                'value'            => 2,
                'unlock_condition' => 'Premium 1100 medals Pi event',
            ],
            [
                'name'             => 'Alien Egg',
                'tier'             => 'Epic',
                'bonus_type'       => 'Enemy Health Level Skip',
                'value'            => 2,
                'unlock_condition' => 'Earn 700 medals Invaders event',
            ],
            [
                'name'             => 'Monolith',
                'tier'             => 'Epic',
                'bonus_type'       => 'Ultimate Damage',
                'value'            => 5,
                'unlock_condition' => 'Premium 1100 medals Invaders event',
            ],
            [
                'name'             => 'Champion Badge',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 10,
                'unlock_condition' => 'Finish P4 in Champion',
            ],
            [
                'name'             => 'Tower Master',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Health',
                'value'            => 10,
                'unlock_condition' => 'Finish P4 in Legend',
            ],
            [
                'name'             => 'T: XI Resonance',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Defense Absolute',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T11',
            ],
            [
                'name'             => 'T: XII Chrono',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Lab Speed',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T12',
            ],
            [
                'name'             => 'T: XIII Hyper',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Coins',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T13',
            ],
            [
                'name'             => 'T: XIV Arcane',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Damage',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T14',
            ],
            [
                'name'             => 'T: XV Celestial',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Crit Factor',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T15',
            ],
            [
                'name'             => 'T: XVI Quantum',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Health',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T16',
            ],
            [
                'name'             => 'T: XVII Nebula',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Damage / Meter',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T17',
            ],
            [
                'name'             => 'T: XVIII Singularity',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Lab Speed',
                'value'            => 10,
                'unlock_condition' => 'Beat w4500 in T18',
            ],
            [
                'name'             => 'Legend Badge',
                'tier'             => 'Legendary',
                'bonus_type'       => 'Crit Factor',
                'value'            => 10,
                'unlock_condition' => 'Win Legend',
            ],
        ];

        foreach ($relics as $row) {
            // 1️⃣ Resolve (or create) the tier
            $tierId = Tier::where(['name' => $row['tier']])->value('id');

            // 2️⃣ Resolve the bonus type (assumes BonusTypeSeeder has run)
            $bonusTypeId = BonusType::where('name', $row['bonus_type'])->value('id');

            // 3️⃣ Create the relic
            $relic = Relic::factory()->create([
                'name'             => $row['name'],
                'tier_id'          => $tierId,
                'unlock_condition' => $row['unlock_condition'],
            ]);

            // 4️⃣ Attach its single bonus through the pivot
            $relic->bonuses()->attach([
                $bonusTypeId => ['value' => $row['value']],
            ]);
        }
    }
}
